CREATE TABLE IF NOT EXISTS public.record_status (
  record_status_id integer PRIMARY KEY,
  code varchar(30) NOT NULL UNIQUE,
  name varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.file_status (
  file_status_id integer PRIMARY KEY,
  code varchar(40) NOT NULL UNIQUE,
  name varchar(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.transaction_status (
  transaction_status_id integer PRIMARY KEY,
  code varchar(40) NOT NULL UNIQUE,
  name varchar(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rejection_reason (
  rejection_reason_id integer PRIMARY KEY,
  code varchar(50) NOT NULL UNIQUE,
  name varchar(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.log_level (
  log_level_id integer PRIMARY KEY,
  code varchar(30) NOT NULL UNIQUE,
  name varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.log_event_type (
  log_event_type_id integer PRIMARY KEY,
  code varchar(60) NOT NULL UNIQUE,
  name varchar(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.files (
  file_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name varchar(255) NOT NULL UNIQUE,
  original_path varchar(1000),
  processed_path varchar(1000),
  file_date date,
  file_status_id integer NOT NULL REFERENCES public.file_status(file_status_id),
  total_records integer NOT NULL DEFAULT 0,
  processed_count integer NOT NULL DEFAULT 0,
  rejected_count integer NOT NULL DEFAULT 0,
  started_at timestamptz,
  finished_at timestamptz,
  record_status_id integer NOT NULL DEFAULT 1 REFERENCES public.record_status(record_status_id),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.transactions (
  transaction_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id bigint NOT NULL REFERENCES public.files(file_id),
  line_number integer NOT NULL,
  raw_account varchar(100),
  raw_amount varchar(100),
  raw_date varchar(100),
  account varchar(10),
  amount numeric(18, 2),
  transaction_date date,
  transaction_status_id integer NOT NULL REFERENCES public.transaction_status(transaction_status_id),
  processed_unique_key varchar(255) UNIQUE,
  record_status_id integer NOT NULL DEFAULT 1 REFERENCES public.record_status(record_status_id),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.transaction_rejections (
  transaction_rejection_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id bigint NOT NULL REFERENCES public.transactions(transaction_id),
  rejection_reason_id integer NOT NULL REFERENCES public.rejection_reason(rejection_reason_id),
  message varchar(1000),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.transaction_reprocess_history (
  reprocess_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id bigint NOT NULL REFERENCES public.transactions(transaction_id),
  previous_amount numeric(18, 2),
  new_amount numeric(18, 2) NOT NULL,
  previous_status_id integer NOT NULL REFERENCES public.transaction_status(transaction_status_id),
  new_status_id integer NOT NULL REFERENCES public.transaction_status(transaction_status_id),
  previous_rejection_summary varchar(1000),
  new_rejection_summary varchar(1000),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.processing_logs (
  log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id bigint REFERENCES public.files(file_id),
  transaction_id bigint REFERENCES public.transactions(transaction_id),
  log_level_id integer NOT NULL REFERENCES public.log_level(log_level_id),
  log_event_type_id integer NOT NULL REFERENCES public.log_event_type(log_event_type_id),
  message varchar(1000) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_files_file_status_id ON public.files (file_status_id);
CREATE INDEX IF NOT EXISTS idx_files_record_status_id ON public.files (record_status_id);
CREATE INDEX IF NOT EXISTS idx_files_created ON public.files (created_at, file_id);
CREATE INDEX IF NOT EXISTS idx_transactions_file_id ON public.transactions (file_id);
CREATE INDEX IF NOT EXISTS idx_transactions_file_line ON public.transactions (file_id, line_number);
CREATE INDEX IF NOT EXISTS idx_transactions_file_status ON public.transactions (file_id, transaction_status_id);
CREATE INDEX IF NOT EXISTS idx_transactions_transaction_status_id ON public.transactions (transaction_status_id);
CREATE INDEX IF NOT EXISTS idx_transactions_record_status_id ON public.transactions (record_status_id);
CREATE INDEX IF NOT EXISTS idx_transaction_rejections_transaction_id
  ON public.transaction_rejections (transaction_id);
CREATE INDEX IF NOT EXISTS idx_transaction_rejections_rejection_reason_id
  ON public.transaction_rejections (rejection_reason_id);
CREATE INDEX IF NOT EXISTS idx_transaction_reprocess_history_transaction_id
  ON public.transaction_reprocess_history (transaction_id);
CREATE INDEX IF NOT EXISTS idx_processing_logs_file_id ON public.processing_logs (file_id);
CREATE INDEX IF NOT EXISTS idx_processing_logs_transaction_id ON public.processing_logs (transaction_id);
CREATE INDEX IF NOT EXISTS idx_processing_logs_log_level_id ON public.processing_logs (log_level_id);
CREATE INDEX IF NOT EXISTS idx_processing_logs_log_event_type_id
  ON public.processing_logs (log_event_type_id);
CREATE INDEX IF NOT EXISTS idx_processing_logs_created
  ON public.processing_logs (created_at, log_id);

INSERT INTO public.record_status (record_status_id, code, name) VALUES
  (1, 'ACTIVO', 'Activo'),
  (2, 'INACTIVO', 'Inactivo')
ON CONFLICT (record_status_id) DO UPDATE
SET code = EXCLUDED.code, name = EXCLUDED.name;

INSERT INTO public.file_status (file_status_id, code, name) VALUES
  (1, 'DISPONIBLE', 'Disponible'),
  (2, 'PROCESANDO', 'Procesando'),
  (3, 'PROCESADO', 'Procesado'),
  (4, 'PROCESADO_CON_RECHAZOS', 'Procesado con rechazos'),
  (5, 'ERROR', 'Error')
ON CONFLICT (file_status_id) DO UPDATE
SET code = EXCLUDED.code, name = EXCLUDED.name;

INSERT INTO public.transaction_status (transaction_status_id, code, name) VALUES
  (1, 'PROCESADO', 'Procesado'),
  (2, 'RECHAZADA', 'Rechazada')
ON CONFLICT (transaction_status_id) DO UPDATE
SET code = EXCLUDED.code, name = EXCLUDED.name;

INSERT INTO public.rejection_reason (rejection_reason_id, code, name) VALUES
  (1, 'CUENTA_VACIA', 'Cuenta vacia'),
  (2, 'CUENTA_INVALIDA', 'Cuenta invalida'),
  (3, 'MONTO_VACIO', 'Monto vacio'),
  (4, 'MONTO_INVALIDO', 'Monto invalido'),
  (5, 'FECHA_VACIA', 'Fecha vacia'),
  (6, 'FECHA_INVALIDA', 'Fecha invalida'),
  (7, 'DUPLICADO', 'Duplicado'),
  (8, 'FILA_CORRUPTA', 'Fila corrupta'),
  (9, 'ESTRUCTURA_INVALIDA', 'Estructura invalida')
ON CONFLICT (rejection_reason_id) DO UPDATE
SET code = EXCLUDED.code, name = EXCLUDED.name;

INSERT INTO public.log_level (log_level_id, code, name) VALUES
  (1, 'INFO', 'Informacion'),
  (2, 'SUCCESS', 'Exito'),
  (3, 'WARNING', 'Advertencia'),
  (4, 'ERROR', 'Error')
ON CONFLICT (log_level_id) DO UPDATE
SET code = EXCLUDED.code, name = EXCLUDED.name;

INSERT INTO public.log_event_type (log_event_type_id, code, name) VALUES
  (1, 'FILE_DETECTED', 'Archivo detectado'),
  (2, 'FILE_VALIDATION_FAILED', 'Validacion de archivo fallida'),
  (3, 'FILE_PROCESS_STARTED', 'Procesamiento de archivo iniciado'),
  (4, 'ROW_PROCESSED', 'Fila procesada'),
  (5, 'ROW_REJECTED', 'Fila rechazada'),
  (6, 'FILE_PROCESS_FINISHED', 'Procesamiento de archivo finalizado'),
  (7, 'TRANSACTION_REPROCESS_STARTED', 'Reproceso de transaccion iniciado'),
  (8, 'TRANSACTION_REPROCESS_FINISHED', 'Reproceso de transaccion finalizado'),
  (9, 'PROCESS_ERROR', 'Error de procesamiento')
ON CONFLICT (log_event_type_id) DO UPDATE
SET code = EXCLUDED.code, name = EXCLUDED.name;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS files_set_updated_at ON public.files;
CREATE TRIGGER files_set_updated_at
  BEFORE UPDATE ON public.files
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS transactions_set_updated_at ON public.transactions;
CREATE TRIGGER transactions_set_updated_at
  BEFORE UPDATE ON public.transactions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.record_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.file_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rejection_reason ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.log_level ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.log_event_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_rejections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_reprocess_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.processing_logs ENABLE ROW LEVEL SECURITY;
